name: Feature request
description: Request an enhancement for the edge layer.
title: "[feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: context
    attributes:
      label: Context
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true
  - type: textarea
    id: risks
    attributes:
      label: Risks and dependencies
